htl_immobilier_homepage:
    path:     /
    defaults: { _controller: HTLImmobilierBundle:Default:index }
accueil:
    path:     /front/bien/accueil
    defaults: { _controller: HTLImmobilierBundle:Front:accueil }
<<<<<<< HEAD
accueiladmin:
    path:     /admin/bien/accueil
    defaults: { _controller: HTLImmobilierBundle:Reservation:accueil }
listeproposition:
    path:     /admin/bien/listeproposition
    defaults: { _controller: HTLImmobilierBundle:Reservation:listeproposition }
=======
accueilprop:
    path:     /admin/bien/accueil
    defaults: { _controller: HTLImmobilierBundle:Reservation:accueil }
>>>>>>> c7dea3f39afe44c3fc02f69a517e5def0b23e2cb
search:
    path:     /front/bien/search
    defaults: { _controller: HTLImmobilierBundle:Front:searchBien }
reserver:
    path:     /front/bien/
    defaults: { _controller: HTLImmobilierBundle:Front:reserverBien }
listebien:
    path:     /front/bien/listebien
    defaults: { _controller: HTLImmobilierBundle:Front:listeBien }
searchprix:
<<<<<<< HEAD
    path:     /front/bien/pri
=======
    path:     /front/bien/prix
>>>>>>> c7dea3f39afe44c3fc02f69a517e5def0b23e2cb
    defaults: { _controller: HTLImmobilierBundle:Front:searchPrix}
searchlocalite:
    path:     /front/bien/localite
    defaults: { _controller: HTLImmobilierBundle:Front:searchLocalite }
listeadmin:
    path:     /front/bien/admin
    defaults: { _controller: HTLImmobilierBundle:Front:listeAdmin }
listereservation:
    path:     /front/bien/reservation
    defaults: { _controller: HTLImmobilierBundle:Front:listeReservation }
<<<<<<< HEAD

=======
details:
    path:     /front/bien/details
    defaults: { _controller: HTLImmobilierBundle:Front:detailsReservation }
>>>>>>> c7dea3f39afe44c3fc02f69a517e5def0b23e2cb
contrat:
    path:     /front/bien/contrat
    defaults: { _controller: HTLImmobilierBundle:Front:contratReservation }
listetype:
    path:     /front/bien/typebien
    defaults: { _controller: HTLImmobilierBundle:Front:listTypebien }
listelocalite:
    path:     /front/bien/listelocalite
    defaults: { _controller: HTLImmobilierBundle:Front:listelocalite }
pdf:
    path:     /front/bien/pdf
    defaults: { _controller: HTLImmobilierBundle:Front:convertoPdf }
afficherpdf:
    path:     /front/bien/afficherpdf
    defaults: { _controller: HTLImmobilierBundle:Front:afficherpdf }
login:
    path:     /admin/login
    defaults: { _controller: HTLImmobilierBundle:Admin:log }
<<<<<<< HEAD

user:
    path:     /test
    defaults: { _controller: HTLImmobilierBundle:Admin:loginconnect }
=======
listebienadmin:
    path:     /admin/listebien
    defaults: { _controller: HTLImmobilierBundle:Admin:listBien }
    
addlocalite:
    path:     /admin/addlocalite
    defaults: { _controller: HTLImmobilierBundle:Admin:addlocalite }
    
addtypebien:
    path:     /admin/addtypebien
    defaults: { _controller: HTLImmobilierBundle:Admin:addtypebien }
    
addbien:
    path:     /admin/addbien
    defaults: { _controller: HTLImmobilierBundle:Admin:addbien }
>>>>>>> c7dea3f39afe44c3fc02f69a517e5def0b23e2cb
    

