<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
        {
                     public function FindAllBienlocalitetype() {

                    return $this->getEntityManager()
                        ->createQuery(
                            'SELECT b, i FROM HTLImmobilierBundle:Bien b left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1')
                        ->getResult();

                            }
<<<<<<< HEAD
                            public function ListeBien() {

                    return $this->getEntityManager()
                        ->createQuery(
                            'SELECT b, i FROM HTLImmobilierBundle:Bien b left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 or b.etat=0')
                        ->getResult();

                            }
=======
>>>>>>> c7dea3f39afe44c3fc02f69a517e5def0b23e2cb

            public function FindAllBienlocalitetypeid($id)
            {

                    return $this->getEntityManager()
                        ->createQuery('SELECT b, i FROM HTLImmobilierBundle:Bien b left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 and b.id=:id')
                        ->setParameter('id',$id)->execute();

        }
          public function FindAllBientypebyid($libelletype)
            {

                    return $this->getEntityManager()
                        ->createQuery('SELECT b, i FROM HTLImmobilierBundle:Bien b left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 and t.libelletype=:libelletype')
                        ->setParameter('libelletype',$libelletype)->execute();

        }
        public function FindAllBienprix($prixlocation,$libellelocalite,$libelletype,$description)
            {   return $this->getEntityManager()->createQuery(
        'SELECT b, i FROM HTLImmobilierBundle:Bien b
                left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 AND b.description LIKE :description AND l.libellelocalite=:libellelocalite and t.libelletype=:libelletype and b.prixlocation BETWEEN (:prixlocation-30000) and (:prixlocation+30000)'
                        )
                    ->setParameters(array('prixlocation'=>$prixlocation,'libellelocalite'=>$libellelocalite,'libelletype'=>
                                            $libelletype,'description'=>'%'.$description.'%'
                                            ))
                        ->execute();
                }

            public function FindAllBiendescription($description)
            {

                    return $this->getEntityManager()
                        ->createQuery(
                            'SELECT b, i FROM HTLImmobilierBundle:Bien b
                left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 and b.description LIKE :description'
                        )
                        ->setParameter('description','%'.$description.'%')->execute();

                }
            public function FindAllBiensansdescription($prixlocation,$libellelocalite,$libelletype)
            {

                    return $this->getEntityManager()
                        ->createQuery(

                    'SELECT b, i FROM HTLImmobilierBundle:Bien b
                left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 and b.prixlocation=:prixlocation AND
                        t.libelletype=:libelletype AND l.libellelocalite=:libellelocalite'
                        )
                        ->setParameters(array('prixlocation'=>$prixlocation,'libellelocalite'=>$libellelocalite,'libelletype'=>
                                            $libelletype
                                            ))
                        ->execute();
                }

            public function FindAllBienprixlocation($prixlocation)
            {

                    return $this->getEntityManager()
                        ->createQuery(
        'SELECT b, i FROM HTLImmobilierBundle:Bien b
                left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 and b.prixlocation BETWEEN (:prixlocation-30000) and (:prixlocation+30000)  '
                        )
                        ->setParameter('prixlocation',$prixlocation)->execute();

                }

}

/*
             return $this->getEntityManager()
                ->createQueryBuilder()
                 ->SELECT('b','l','t','i')
                 ->FROM('HTLImmobilierBundle:Bien','b')
                 ->FROM('HTLImmobilierBundle:Image','i')
                 ->leftJoin('b.libellelocalite','l')
                 ->leftJoin('b.typebien','t')
                 ->leftJoin('i.bien','im')
                 ->where('l=:libellelocalite')
                 ->orwhere('t=:libelletype')
                 ->orwhere('b.prixlocation=:prixlocation')
                 ->orwhere('b.description LIKE :description')
 ->setParameters(array('prixlocation'=>$prixlocation,'libellelocalite'=>$libellelocalite,'libelletype'=>
                         $libelletype,'description'=>'%'.$description.'%'
                      ))
                 ->getQuery()->getResult();*/

