<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * ContratProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratProRepository extends \Doctrine\ORM\EntityRepository
{
}
