<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * DemandeBailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeBailRepository extends \Doctrine\ORM\EntityRepository
{
}
