<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
      public function FindAllReservation($id) {

                    return $this->getEntityManager()
                        ->createQuery(
                            /*'SELECT c.nomComplet,c.adresse,b.typebien,b.libellelocalite,b.libelletype,b.prixlocation,  WHERE r.etat = 0')*/
                            'SELECT r FROM HTLImmobilierBundle:Reservation r WHERE r.id =:id')
                        ->setParameter('id',$id)
                        ->getResult();

                }

}
