<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * TermecontratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermecontratRepository extends \Doctrine\ORM\EntityRepository
{
}
