<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * TypebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypebienRepository extends \Doctrine\ORM\EntityRepository
{
     public function FindAllBientypebien($libelletype)
    {

             return $this->getEntityManager()
                ->createQuery(
                    'SELECT b, i FROM HTLImmobilierBundle:Bien b
        left Join b.images i Join b.typebien t Join b.libellelocalite l WHERE b.etat = 1 and t.libelletype=:libelletype'
                )
                 ->setParameter('libelletype',  $libelletype)->execute();

        }
}
